[package]
name = "rand-http"
version = "0.1.0"
authors = ["Leo <leo881003@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.3"
tokio = { version = "1.6.0", features = ["full"] }
warp = "0.3.1"
